/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author shagg
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
        setSize(1200,900);
        setResizable(false);
        setTitle("Administrador");
        setLocationRelativeTo(null);
                ImageIcon wallpaper = new ImageIcon("src/images/FondoC.jpg");
        Icon Icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(),
                jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(Icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton_Contabilidad = new javax.swing.JButton();
        jButton_Comercial = new javax.swing.JButton();
        jButton_THumano = new javax.swing.JButton();
        jButton_ConfContabilidad = new javax.swing.JButton();
        jButton_Reportes = new javax.swing.JButton();
        jButton_ConfThumano = new javax.swing.JButton();
        jButton_Nusuario = new javax.swing.JButton();
        jButton_ConfComercial = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1200, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nuevo Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 830, 190, 50));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Talento Humano");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 210, 210, 50));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 25)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ingreso a Contabilidad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 270, 50));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("De Talento Humano");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 560, 240, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 25)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Configuración");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 530, 170, 30));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 25)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Configuración");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, 170, -1));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 25)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Reportes");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 830, 120, 50));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 25)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Ingreso a Ventas");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 210, 50));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 25)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("De Contabilidad");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 560, 190, -1));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 25)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Configuración");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, 170, 30));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 25)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("De Ventas");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 560, 120, -1));

        jButton_Contabilidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/conta (2).png"))); // NOI18N
        jButton_Contabilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ContabilidadActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Contabilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 110, 110));

        jButton_Comercial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Comercial (2).png"))); // NOI18N
        jButton_Comercial.setPreferredSize(new java.awt.Dimension(25, 25));
        getContentPane().add(jButton_Comercial, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 110, 110));

        jButton_THumano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Talento Humano (2).png"))); // NOI18N
        getContentPane().add(jButton_THumano, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 90, 110, 110));

        jButton_ConfContabilidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/configuracion Cont (2).png"))); // NOI18N
        jButton_ConfContabilidad.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        getContentPane().add(jButton_ConfContabilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 110, 110));

        jButton_Reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Reportes (2).png"))); // NOI18N
        jButton_Reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ReportesActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 700, 110, 110));

        jButton_ConfThumano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Config Talento (2).png"))); // NOI18N
        jButton_ConfThumano.setText("jButton1");
        getContentPane().add(jButton_ConfThumano, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 400, 110, 110));

        jButton_Nusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Nuevousuario (2).png"))); // NOI18N
        getContentPane().add(jButton_Nusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 700, 110, 110));

        jButton_ConfComercial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Conf Comercial (2).png"))); // NOI18N
        getContentPane().add(jButton_ConfComercial, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 110, 110));

        jButton9.setBackground(new java.awt.Color(255, 51, 51));
        jButton9.setText("Salir");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, 75, 30));

        jLabel_Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FondoC.jpg"))); // NOI18N
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton_ReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ReportesActionPerformed

    private void jButton_ContabilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ContabilidadActionPerformed
    InfContabilidad infcont = new InfContabilidad();
    infcont.setVisible(true);
    dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ContabilidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton_Comercial;
    private javax.swing.JButton jButton_ConfComercial;
    private javax.swing.JButton jButton_ConfContabilidad;
    private javax.swing.JButton jButton_ConfThumano;
    private javax.swing.JButton jButton_Contabilidad;
    private javax.swing.JButton jButton_Nusuario;
    private javax.swing.JButton jButton_Reportes;
    private javax.swing.JButton jButton_THumano;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Wallpaper;
    // End of variables declaration//GEN-END:variables
}
